name: Deploy on Raspberry (self-hosted)

on:
  push:
    branches: [ "main" ]   # troque se seu branch for outro
  workflow_dispatch:        # permite rodar manualmente no botão "Run workflow"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]   # envia para o seu runner do Pi
    steps:
      - name: Pull & restart site
        run: |
          set -e
          cd /home/dawid/app/Unilife-main/Unilife-main
          git fetch --all
          git reset --hard origin/main
          . .venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput || true
          sudo systemctl restart django-runserver
