# Generated by Django 5.2.5 on 2025-08-30 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='cadastros',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Personais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personais', to='contas.cadastros')),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='contas.cadastros')),
                ('id_treino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='contas.treinos')),
            ],
        ),
    ]
